"""Persona archetypes for think-aloud protocol simulation."""

import random

ARCHETYPES = [
    {
        "id": "traditional_craftsperson",
        "name": "Traditional Craftsperson",
        "role": "Senior Visual Designer",
        "years": 15,
        "industry": "Branding / Print",
        "ai_comfort": "resistant — rarely uses AI, prefers manual craft",
        "motivation": "My boss forwarded me this link and said 'take it'. I'm skeptical but willing.",
        "think_style": "Measured and deliberate. Notices craft details. Skeptical of AI hype.",
        "sae_center": 0, "sae_spread": 0.3,
        "epias_center": 2.5, "epias_spread": 0.8,
        "age_ranges": ["35-44", "45-54"],
        "role_variants": ["Senior Visual Designer", "Lead Brand Designer", "Art Director"],
    },
    {
        "id": "curious_explorer",
        "name": "Curious Explorer",
        "role": "Junior UX Designer",
        "years": 2,
        "industry": "Tech startup",
        "ai_comfort": "enthusiastic beginner — excited about AI but still figuring it out",
        "motivation": "Genuinely curious where I stand. Saw John Maeda share this and want to try it.",
        "think_style": "Excitable, asks lots of questions, reads everything carefully.",
        "sae_center": 1, "sae_spread": 0.5,
        "epias_center": 1.2, "epias_spread": 0.6,
        "age_ranges": ["under-25", "25-34"],
        "role_variants": ["Junior UX Designer", "UX Design Intern", "Associate Product Designer"],
    },
    {
        "id": "daily_user",
        "name": "Daily AI User",
        "role": "Product Designer",
        "years": 6,
        "industry": "SaaS",
        "ai_comfort": "comfortable — uses ChatGPT/Claude daily for work tasks",
        "motivation": "Want to calibrate where I actually stand vs. where I think I am.",
        "think_style": "Analytical, compares options carefully, appreciates clear categorization.",
        "sae_center": 2, "sae_spread": 0.5,
        "epias_center": 2.0, "epias_spread": 0.7,
        "age_ranges": ["25-34", "35-44"],
        "role_variants": ["Product Designer", "Senior Product Designer", "UX/UI Designer"],
    },
    {
        "id": "app_builder",
        "name": "App Builder",
        "role": "Design Engineer",
        "years": 4,
        "industry": "AI-native startup",
        "ai_comfort": "fluent — builds with Cursor/Claude Code, ships AI-generated components daily",
        "motivation": "Want validation that I'm advanced. Also curious how the framework categorizes me.",
        "think_style": "Fast, critical of UX friction, notices technical implementation details.",
        "sae_center": 3, "sae_spread": 0.5,
        "epias_center": 3.0, "epias_spread": 0.8,
        "age_ranges": ["25-34"],
        "role_variants": ["Design Engineer", "Creative Technologist", "Full-Stack Designer"],
    },
    {
        "id": "design_leader",
        "name": "Design Leader",
        "role": "VP of Design",
        "years": 18,
        "industry": "Enterprise Tech",
        "ai_comfort": "moderate — uses AI occasionally but thinks more about team adoption",
        "motivation": "Evaluating this tool for my team of 40 designers. Thinking about team-wide rollout.",
        "think_style": "Strategic, thinks about scalability and team implications, less personal.",
        "sae_center": 1, "sae_spread": 0.4,
        "epias_center": 4.0, "epias_spread": 0.6,
        "age_ranges": ["35-44", "45-54"],
        "role_variants": ["VP of Design", "Head of Design", "Design Director"],
    },
    {
        "id": "career_changer",
        "name": "Career Changer",
        "role": "Aspiring UX Designer",
        "years": 0,
        "industry": "Education transitioning to Tech",
        "ai_comfort": "anxious — knows AI matters but feels behind, worried about job market",
        "motivation": "Job hunting, need to know what skills to learn. Saw this on LinkedIn.",
        "think_style": "Uncertain, reads carefully, sometimes confused by jargon, self-conscious.",
        "sae_center": 1, "sae_spread": 0.6,
        "epias_center": 1.0, "epias_spread": 0.4,
        "age_ranges": ["25-34", "35-44"],
        "role_variants": ["Aspiring UX Designer", "Career Switcher", "UX Bootcamp Student"],
    },
    {
        "id": "ai_native_engineer",
        "name": "AI-Native Engineer",
        "role": "Full-Stack AI Product Builder",
        "years": 3,
        "industry": "AI startup",
        "ai_comfort": "expert — lives in agent workflows, builds with Claude Code and LangGraph",
        "motivation": "Benchmarking myself. Probably going to find this too basic for me.",
        "think_style": "Impatient, skims quickly, critical of simplifications, wants depth.",
        "sae_center": 4, "sae_spread": 0.4,
        "epias_center": 1.5, "epias_spread": 0.7,
        "age_ranges": ["25-34"],
        "role_variants": ["AI Engineer", "ML Product Builder", "AI Product Developer"],
    },
    {
        "id": "agency_creative_director",
        "name": "Agency Creative Director",
        "role": "Creative Director",
        "years": 12,
        "industry": "Advertising agency",
        "ai_comfort": "ambivalent — uses AI for ideation but worries about losing creative soul",
        "motivation": "Want to stay relevant. Half my team uses AI more than me and I need to catch up.",
        "think_style": "Opinionated, values aesthetics, sometimes defensive about craft vs. automation.",
        "sae_center": 1, "sae_spread": 0.5,
        "epias_center": 3.5, "epias_spread": 0.8,
        "age_ranges": ["35-44", "45-54"],
        "role_variants": ["Creative Director", "Executive Creative Director", "Group Creative Director"],
    },
    {
        "id": "ux_researcher",
        "name": "UX Researcher",
        "role": "Senior UX Researcher",
        "years": 8,
        "industry": "Fintech",
        "ai_comfort": "cautious adopter — uses AI for synthesis and analysis, careful about bias",
        "motivation": "Interested in the framework methodology itself. Meta-curious about the UX of this UX tool.",
        "think_style": "Reflective and meta — notices the experience of being assessed, evaluates the assessment.",
        "sae_center": 2, "sae_spread": 0.5,
        "epias_center": 3.0, "epias_spread": 0.7,
        "age_ranges": ["25-34", "35-44"],
        "role_variants": ["Senior UX Researcher", "Lead UXR", "Research Manager"],
    },
    {
        "id": "student_non_designer",
        "name": "Non-Designer Student",
        "role": "CS Graduate Student",
        "years": 1,
        "industry": "Academia",
        "ai_comfort": "high technical skill — comfortable with code and models, less with design terms",
        "motivation": "Academic interest in how designers relate to AI. Writing a paper on AI adoption.",
        "think_style": "Questioning — 'What does this term mean?' Analytical but unfamiliar with design jargon.",
        "sae_center": 3, "sae_spread": 0.7,
        "epias_center": 1.2, "epias_spread": 0.5,
        "age_ranges": ["under-25", "25-34"],
        "role_variants": ["CS Graduate Student", "HCI PhD Student", "AI Researcher"],
    },
]


def instantiate_personas(n_per_archetype: int = 5, seed: int = 42) -> list[dict]:
    """Create concrete persona instances from archetypes."""
    rng = random.Random(seed)
    personas = []

    for arch in ARCHETYPES:
        for i in range(n_per_archetype):
            persona = {
                "archetype_id": arch["id"],
                "archetype_name": arch["name"],
                "role": rng.choice(arch["role_variants"]),
                "years": max(0, arch["years"] + rng.randint(-2, 2)),
                "industry": arch["industry"],
                "ai_comfort": arch["ai_comfort"],
                "motivation": arch["motivation"],
                "think_style": arch["think_style"],
                "age_range": rng.choice(arch["age_ranges"]),
                "sae_center": arch["sae_center"],
                "sae_spread": arch["sae_spread"],
                "epias_center": arch["epias_center"],
                "epias_spread": arch["epias_spread"],
                "instance": i,
            }
            personas.append(persona)

    rng.shuffle(personas)
    return personas
